# Site settings
title: Hybrid SyntaX
email: abbas@hybridsyntax.com
description: > # this means to ignore newlines until "baseurl:"
  Abbas Allahyari's personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hybridsyntax.com" # the base hostname & protocol for your site
twitter_username: hybrid_syntax
github_username:  hybrid-syntax

# Build settings
markdown: kramdown
encoding: utf-8
timezone: Asia/Tehran
auto: true

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/fa
    values:
      layout: default
      lang: fa

permalink: /:title/

