# Site settings
title: Hybrid SyntaX
name: Hybrid SyntaX
email: abbas@hybridsyntax.com
description: > # this means to ignore newlines until "baseurl:"
  Abbas Allahyari's personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hybridsyntax.com" # the base hostname & protocol for your site
twitter_username: hybrid_syntax
github_username:  hybrid-syntax
author: Abbas Allahyari
linkedin_url : ir.linkedin.com/pub/abbas-allahyari/69/b09/660
googleplus_url: https://plus.google.com/u/0/117835603692279264063/
# Build settings
markdown: kramdown
encoding: utf-8
timezone: Asia/Tehran
auto: true

defaults:
  -
    scope:
      type: posts
      path: "en"
    values:
      permalink: "/en/blog/:categories/:title/"
  -
    scope:
      type: posts
      path: "fa"
    values:
      permalink: "/fa/blog/:categories/:title/"



t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
  fa:
    home:
      name: "خانه"
      url: "/fa/"
    about:
      name: "درباره من"
      url: "/about/"




slugify: true

metas:
  tag:
    slugify: false
    plural: tags
  category:
    slugify: true
    plural: categories
