# Site settings
title: Abbas Allahyari
name: Abbas Allahyari
email: abbas@abbasai.com
description: > # this means to ignore newlines until "baseurl:"
  Abbas Allahyari's personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hybridsyntax.com" # the base hostname & protocol for your site
twitter_username: hybrid_syntax
github_username:  hybrid-syntax
author: Abbas Allahyari
linkedin_url : Http://ir.linkedin.com/pub/abbas-allahyari/69/b09/660
googleplus_url: https://plus.google.com/u/0/117835603692279264063/
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
encoding: utf-8
timezone: Asia/Tehran
#auto: true

defaults:
  -
    scope:
      type: posts
      path: "en"
    values:
      layout: default
      #permalink: en/blog/:title.html

  -
    scope:
      type: posts
      path: "fa"
    values:
      layout: default
      #permalink: fa/blog/:title.html


permalink: :title.html

t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
  fa:
    home:
      name: "خانه"
      url: "/fa/"
    about:
      name: "درباره من"
      url: "/about/"




slugify: true

metas:
  tag:
    slugify: false
    plural: tags
  category:
    slugify: true
    plural: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

tag_title_prefix: 'posts tagged '
category_title_prefix: 'posts under '
tag_dir: blog/tag
tag_inc_ext: true
category_dir: blog/category
category_inc_ext: true

## This part is for local only ##
exclude: [fa/blog/category,fa/blog/tag,en/blog/category,en/blog/tag,README.md]
show_drafts: true
future: true
#lsi: true
